apps/urls.py
from django.urls import path
from apps.views.views import *
from apps.views.items_view import *
from apps.views.cart_views import *
from apps.views.order_views import *
from apps.rest_api.items import *
from apps.rest_api.users import *
from apps.rest_api.cart import *
from apps.rest_api.orders import *









urlpatterns = [
    path('signup/',signup,name='signup'),
    path('verify/<str:email>/',verify,name='verify'),
    # path('thankyou/',index)
    path('logout/',logout_user,name='logout'),
    path('signin/',signin,name='signin'),
    # path('home/',home,name='home'),
    path('user_details/',user_details,name='user_details'),
    path('subscriber/',subscribers,name='subscriber'),

    ###### Home pageurls
    
    path('home/',item_list,name='home'),
    path('item_not_available/',make_item_unavailable,name='make_item_unavailable'),
    path('item_available/',make_item_available,name='make_item_available'),
    path('filter/<int:category_id>/', filter_items, name='filter_items'),


    ############### Cart page urls ######################

    path('cart/<int:item_id>/',add_to_cart,name='cart'),
    path('cart_list/',cart_list,name='cart_list'),
    path('update_cart/<int:item_id>/',update_cart_item,name='update_cart_item'),
    path('cart_delete_all/',delete_cart_all_items,name='cart_delete_all'),
    path('delete_single_cart_item/<int:item_id>/',delete_single_cart_item,name='delete_single_cart_item'),

    ############ Order page urls #######################

   
    path('checkout/', checkout, name='order'),


    ####################### rest views ########################

    path('item_list/',ItemList.as_view(), name='Item List'),
    
    ######################## user rest view ###################

    path('rest_signup/',SignUpView.as_view(), name='rest_signup'),

    path('rest_signin/',SigninView.as_view(),name='rest_signin'),

    path('rest_logout/',LogoutView.as_view(), name='rest_logout'),

    path('rest_verify/<str:email>/',VerifyOtpView.as_view(), name='VerifyRestEmail'),

    path('rest_subscriber/',Subscribers.as_view(),name='rest_subscribers'),


    ############################# Categories #######################

    path('rest_category/',CategoryListView.as_view(),name='rest_category'),

    ############################ Carts #############################

    path('rest_cart/<int:user_id>/',CartListView.as_view(),name='rest_cart'),

    path('restadd_cart/<int:user_id>/',CartAddView.as_view(),name='rest_cart_add'),

    path('restupdate_cart/<int:pk>/<int:user_id>/',CartItemUpdateView.as_view(),name='rest_cart_update'),

    path('delete_cart/<int:pk>/',CartDestroyView.as_view(),name='rest_cart_destroy'),

    ########################### Order Api #############################

    path('rest_order/',OrderAdd.as_view(),name="rest_order")



]

food_delivery/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
# from apps.rest_api.

# from rest_framework_swagger.views import get_swagger_view

from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Meal Mate",
        default_version='v1',
        description="This app is used to order food from the native restaurant",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('swagger.json/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # path('swagger/', get_swagger_view(title='My API')),
    
]

apps/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from apps.models import *
#######################Sign UP form##################################

class SignUpForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'UserName'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input--style-2','placeholder': 'Password'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input--style-2','placeholder': 'Email'}))
    phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class': 'input--style-2','placeholder': 'Phone Number'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2','placeholder': 'Address'}))

    class Meta:
        model = User
        fields = ('username','password', 'email', 'phone_number', 'address',)


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
    
################# verifying the otp form #########################


class VerifyOTPForm(forms.Form):
    otp = forms.CharField(max_length=6)


###################Signin form#################################

class SignInForm(forms.Form):
    username= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'UserName'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input--style-2','placeholder': 'Password'}))
    class Meta:
        model = User
        fields = ('username', 'password')




################## changing the user_details form #####################

class ChangeUserDetails(forms.Form):
    # username = forms.CharField(max_length=100,label='Username:')
    username= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'UserName'}))
    # email = forms.EmailField(label='Email:')
    email= forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input--style-2', 'placeholder': 'Email'}))
    # phone_number = forms.IntegerField(label="Phone Number:")
    phone_number= forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input--style-2', 'placeholder': 'Phone Number'}))
    # address = forms.CharField(max_length=100,label = 'Address:')
    address= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Address'}))
    display_picture = forms.FileField(label='Change Display Picture',required=False)


#################### Order Form #################################

class OrderForm(forms.Form):
    PAYMENT_CHOICES =(   
    ("CASH ON DELIVERY", "COD"),
    ("UPI", "UPI"),
    ("CARD", "CARD"),
    )

    first_name= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'First Name'}))

    last_name= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Last Name'}))

    address= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Address'}))

    zip_code= forms.CharField(widget=forms.NumberInput(attrs={'class': 'input--style-2', 'placeholder': 'Zip Code'}))

    place= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Place'}))

    payment_method = forms.ChoiceField(label='Payment Method', choices=PAYMENT_CHOICES, widget=forms.Select(attrs={'class': 'form-control', 'required': True}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None) # Get the user object from kwargs
        super().__init__(*args, **kwargs)
        if self.user:
            self.fields['address'].initial = self.user.address # Set the default value of the address field to the user's address

    def save(self, *args, **kwargs):
        # Save the order details here
        pass



class SubscribersForm(forms.Form):
    subscriber_email = forms.EmailField(widget=forms.EmailInput(attrs={'class': "subscribe-input", 'placeholder': 'Enter Your Email'}))
    

apps/views/cart_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from apps.models import *



############### Adding to the Cart ########################

def add_to_cart(request, item_id):
    # Check if user is authenticated
    if not request.user.is_authenticated and request.user.token and request.user.is_logged_in or request.user.is_superuser:
        return redirect('signin')

    # Retrieve the item from the database
    item = Items.objects.get(pk=item_id)

    # Check if the item is already in the user's cart
    cart_item, created = Cart.objects.get_or_create(item=item, user=request.user)
    if not created:
        # If the item already exists in the user's cart, increase the quantity
        cart_item.quantity += 1
        cart_item.save()

    # Redirect back to the previous page
    return redirect(request.META.get('HTTP_REFERER', 'home'))




##################### Cart List ######################### 


# def cart_list(request):
#     cart_list = Cart.objects.get(user= request.user)

#     if request.user.is_authenticated and request.user.token and  request.user.is_logged_in:
#         cart_list = Cart.objects.get(user= request.user)

#     return render(request,'cart.html',{'cart_list':cart_list})


def cart_list(request):
    if request.user.is_authenticated and request.user.token and request.user.is_logged_in or request.user.is_superuser:
        cart_items = Cart.objects.filter(user=request.user)
        cart_count = Cart.objects.filter(user=request.user).count()
        subtotal = 0

        for item in cart_items:
            subtotal += item.item.item_price * item.quantity
            
        context = {'cart_items': cart_items,'subtotal': subtotal,'cart_count': cart_count}
        return render(request, 'cart.html', context)
    else:
        return redirect('signin')



############################### Update Cart Items ###############################


def update_cart_item(request, item_id):
    # Check if user is authenticated
    if not request.user.is_authenticated and request.user.token and request.user.is_logged_in  or request.user.is_superuser:
        return redirect('signin')

    # Retrieve the cart item from the database
    cart_item = Cart.objects.get(pk=item_id, user=request.user)

    # Update the quantity based on the action parameter
    action = request.POST.get('action')
    if action == 'increase':
        cart_item.quantity += 1
    elif action == 'decrease':
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
        else:
            # If the quantity reaches 0, remove the item from the cart
            cart_item.delete()
            return redirect('cart_list')

    # Save the updated cart item
    cart_item.save()

    # Redirect to the cart page
    return redirect('cart_list')



###################################### Cart Delete ##############################


def delete_cart_all_items(request):
    cart_delete = Cart.objects.filter(user=request.user)
    cart_delete.delete()
    return redirect('cart_list')



def delete_single_cart_item(request,item_id):
    Cart.objects.filter(pk=item_id).delete()

    return redirect('cart_list')

templates/ThankingPage.html
{% extends 'layout.html' %}
{% block content %}
{% include 'navbar.html' %}
<div class="background-order d-flex" style="width: 95%;margin-top: -7%;">
  <div class="container d-flex flex-column justify-content-center">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <form method="POST">
          {% csrf_token %}
          <h1 class="text-decoration-underline mb-4">Enter Your Details:</h1>
          <div class="mb-3">
            <!-- {{ form.first_name.label_tag }} -->
            {{ form.first_name }}
          </div>
          <div class="mb-3">
            <!-- {{ form.last_name.label_tag }} -->
            {{ form.last_name }}
          </div>
          <div class="mb-3">
            <!-- {{ form.address.label_tag }} -->
            {{ form.address }}
          </div>
          <div class="mb-3">
            <!-- {{ form.zipcode.label_tag }} -->
            {{ form.zipcode }}
          </div>
          <div class="mb-3">
            <!-- {{ form.place.label_tag }} -->
            {{ form.place }}
          </div>
          <div class="mb-3">
            <!-- {{ form.payment_mode.label_tag }} -->
            {{ form.payment_mode }}
          </div>
         
          <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/cart.html
{% extends 'layout.html' %}
{% block content %}

{% include 'navbar.html' %}

<h1 class="cartpage-headin">Welcome To Your Cart!!!</h1>

<div class="text-center mt-3 mb-3">

    <a href="{% url 'cart_delete_all' %}"><button class="btn btn-danger">Delete All Items</button></a>

</div>

<div class="d-flex flex-column align-items-center pt-5 pb-5">
    {% for cart in cart_items %}
    <div class="card mb-3" style="width: 70%;">
        <div class="row g-0 p-0">
            <div class="col-md-4" style="width:25%;">
                <img src="{{cart.item.item_image.url}}" class="img-fluid rounded-start" alt="..."
                    style="width: 100%;height: 30vh;">
            </div>
            <div class="col-md-8 d-flex align-items-center">
                <div class="card-body">
                    <b>
                        <h5 class="card-title fw-bolder fs-2"> {{cart.item.item_name}}</h5>
                    </b>
                    <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse mollitia
                        reiciendis dolorum animi sequi vero quasi? Alias commodi nobis saepe hic facilis
                        perspiciatis deserunt
                        totam laboriosam. Temporibus asperiores blanditiis cupiditate! Lorem ipsum dolor sit amet
                        consectetur
                        adipisicing elit. Numquam provident dolorem vel adipisci suscipit delectus accusamus!
                        Tenetur quaerat
                        optio, quia consequuntur consectetur laboriosam harum nesciunt modi blanditiis aut! Minima,
                        earum!</p>
                    <h5 class="card-title fs-3">{{cart.item.item_price}}</h5>


                    <div class="cart-quantity">

                        <form method="POST" action="{% url 'update_cart_item' cart.id %}" style="width:0;">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="decrease">
                            <button class="quantitybutton">-</button>
                        </form>


                        <h4 class="cart-present-quantity">{{cart.quantity}}</h4>
                        <form method="POST" action="{% url 'update_cart_item' cart.id %}" style="width: 0;">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="increase">
                            <button class="quantitybutton">+</button>
                        </form>
                    </div>
                    <a href="{% url 'delete_single_cart_item' cart.id %}"><i class="bi bi-trash3-fill"></i></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>


<div class="footer-cart">
    <h1 class="subtotal">Your Total Ammount: {{subtotal}}</h1>
    <a href="{% url 'order' %}"><button class="checkoutbtn">CHECKOUT</button></a>
</div>


{% endblock %}

templates/checkout.html
{% extends 'layout.html' %}
{% block content %}
{% include 'navbar.html' %}
<div class="background-order d-flex" style="width: 95%;">
    <div class="container d-flex flex-column justify-content-center">
        <div class="row justify-content-center" style="align-items: baseline;">
            <div class="col-lg-6">
                <form method="POST">
                    {% csrf_token %}
                    <h1 class="text-decoration-underline mb-4">Enter Your Details:</h1>
                    <div class="mb-3">
                        <!-- <label for="first_name" class="form-label">First Name</label> -->
                        {{ form.first_name }}
                    </div>
                    <div class="mb-3">
                        <!-- <label for="last_name" class="form-label">Last Name</label> -->
                        {{ form.last_name }}

                    </div>
                    <div class="mb-3">
                        <!-- <label for="address" class="form-label">Address</label> -->
                        {{ form.address }}
                        
                        
                    </div>
                    <div class="mb-3">
                        <!-- <label for="zipcode" class="form-label">Zipcode</label> -->
                        {{ form.zip_code }}
                        
                    </div>
                    <div class="mb-3">
                        <!-- <label for="place" class="form-label">Place</label> -->
                        {{ form.place }}
                        
                    </div>
                    <div class="mb-3">
                        <label for="payment_mode" class="form-label">Payment Mode</label>
                        {{ form.payment_method }}
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6">
                <div class="d-flex flex-column" style="margin-top: 10%;">
                    <h1 class="text-center text-decoration-underline">Your Orders:</h1>
                    {% for cart in cart_items %}
                    <div class="container d-flex flex-column justify-content-center" style="width: 100%; padding: 2%;">
                        <div class="card" style="height: fit-content;">
                            <div class="row g-0 p-0 justify-content-xxl-between">
                                <div class="col-md-4" style="width: 30%;">
                                    <img src="{{cart.item.item_image.url}}" class="img-fluid rounded-start" alt="..." style="width: 100%; height: 20vh;">
                                </div>
                                <div class="col-md-8 d-flex align-items-center">
                                    <div class="card-body p-0">
                                        <h1 class="card-title fw-bolder fs-2">{{cart.item.item_name}}</h1>
                                        <h1 class="card-title fs-3 mb-3">{{cart.item.item_price}} X {{cart.quantity}}</h1>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
            </div>
            <br>
            <br>

            <div style="padding: 1%;">
                <hr>
                <h1 class="text-center mt-2 text-decoration-underline">Your Total Order Ammount is: </h1>
                <!-- <h2 class="text-center">Delivery Charges: $5</h2>
                <h2 class="text-center">GST: $3</h2> -->
                <h2 class="text-center">Totoal Price: {{total}}</h2>
            </div>
        
            

        
        </div>
        
    </div>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Mate</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">
    <title>Meal Mate</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <!-- bootstrap links  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
   <!-- bootstrap links end  -->
    {%load static%}

    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/profile_page.css' %}" type="text/css">

    <!-- <link rel="stylesheet" href="{% static 'css/otp.css' %}" type="text/css"> -->


</head>

<body>
   
    {% block content %}{% endblock %}

    
    <!-- <a href="{% url 'logout' %}"><button>Logout</button></a>
    <a href="{%url 'user_details' %}"><button>Your Account</button></a> -->

    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <!-- <script src="../static/js/global.js"></script> -->
</body>

</html>

templates/navbar.html
{% extends 'layout.html' %}
{% block content %}
<header>
    <img class="logo" src="../static/img/logo.png" alt="">
    <div class="navbar_elements">
        <a href="{% url 'home' %}" style="padding: 1%;">
            <i class="bi bi-house-fill"></i>
        </a>
        {% for category in categories|slice:":4" %}
        <a href="{% url 'filter_items' category.id %}" style="padding: 1%;">
            <h2 class="categories">{{ category.category_name }}</h2>
        </a>
        {% endfor %}
        {% if categories|length > 4 %}
        <div class="dropdown">
            <button class="dropbtn">
                <h3>More Categories</h3>
            </button>
            <div class="dropdown-content">
                {% for category in categories|slice:"4:" %}
                <a href="{% url 'filter_items' category.id %}">
                    <h3>{{ category.category_name }}</h3>
                </a>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
    <div class="nav-logos">

        <a href="{% url 'user_details' %}">
            <i class="bi bi-person-circle"></i>
        </a>

        {% if request.user.is_logged_in %}
        <a href="{% url 'logout' %}">
            <i class="bi bi-box-arrow-left"></i>
        </a>

        {% else %}
        <a href="{% url 'signin' %}" style="padding: 1%;">
            <i class="bi bi-person-fill"></i>
        </a>
        {% endif %}
        
        <a href="{% url 'cart_list' %}" style="padding: 1%;">
            <i class="bi bi-bag-heart-fill"></i>  
        </a>
    <h4>({{ cart_count }})</h4>
    </div>


</header>



{% endblock %}

templates/signin.html
{% extends 'layout.html' %}
{% block content %}
    <div class="page-wrapper bg-red p-t-180 p-b-100 font-robo">
        <div class="wrapper wrapper--w960">
            <div class="card card-2">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title text-center">Get In</h2>
                    <form method="POST">
                        {% csrf_token %}
                        <form method="POST" action="{% url 'signup' %}">
                            {% csrf_token %}
                            {{ form.username }}
                            {{ form.password }}
                            <div class="p-t-30">
                             
                            <button class="btn btn--radius btn--green" type="submit">SignIn</button>

                            </div>
                        </form>
                    </form>
                    
                    <span class="signup-signin-text">Not a member yet?<a href="{% url 'signup' %}" style="text-decoration: none;">SignUp</a></span>
                </div>
            </div>
            
        </div>
    </div>

    {% endblock %}

templates/signup.html
{% extends 'layout.html' %}
{% block content %}
    <div class="page-wrapper bg-red p-t-180 p-b-100 font-robo">
        <div class="wrapper wrapper--w960">
            <div class="card card-2">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title text-center">Register</h2>
                    <form method="POST">
                        {% csrf_token %}
                        <form method="POST" action="{% url 'signup' %}">
                            {% csrf_token %}
                            {{ form.username }}
                            {{ form.password }}
                            {{ form.email }}
                            {{ form.phone_number }}
                            {{ form.address }}
                            <div class="p-t-30">
                             
                            <button class="btn btn--radius btn--green" type="submit">SignUp</button>

                            </div>
                        </form>
                    <br>
                    <br>
                    <span class="signup-signin-text">Not a member yet?<a href="{% url 'signin' %}" style="text-decoration: none;">SignIn</a></span>
                </div>
            </div>
            
        </div>
    </div>

    {% endblock %}

templates/subscriber.html
{% extends 'layout.html' %}
{% block content %}

<div class="subscribe-div">
  <div class="emailinput">
    <form action="{% url 'home' %}" method="POST" class="subscriber-form">
      {% csrf_token %}
      {{ form_context.form.subscriber_email }}
      {% if form_context.form.subscriber_email.errors %}
        <div class="error" style="color:white">{{ form_context.form.subscriber_email.errors }}</div>
      {% endif %}
      <button class="subscribe-btn" type="submit">SUBSCRIBE</button>
    </form>
  </div>
</div>

{% endblock %}

templates/verify.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Meal Mate</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <style>
    HTML CSS JSResult Skip Results Iframe
.height-100 {
    height: 100vh
}
html {
    background-color: #fa4251;
}
body {
    margin-top: 16%;
    background-color: #fa4251;

}

.card {
    width: 500px;
    border: none;
    height: 400px;
    box-shadow: 0px 5px 20px 0px #d2dae3;
    z-index: 1;
    display: flex;
    justify-content: center;
    align-items: center
}

.card h6 {
    color: red;
    font-size: 28px;
}
div {
    font-size: large;
}
.inputs input {
    width: 70%;
    height: 50px;
}

input[type=number]::-webkit-inner-spin-button,
input[type=number]::-webkit-outer-spin-button {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    margin: 0
}

.card-2 {
    background-color: #fff;
    padding: 10px;
    width: 350px;
    height: 100px;
    bottom: -50px;
    left: 20px;
    position: absolute;
    border-radius: 5px
}

.card-2 .content {
    margin-top: 50px
}

.card-2 .content a {
    color: red
}

.form-control:focus {
    box-shadow: none;
    border: 2px solid red
}

.validate {
    border-radius: 20px;
    height: 40px;
    background-color: red;
    border: 1px solid red;
    width: 140px
}

  </style>
</head>
<body>

  <div class="container height-100 d-flex justify-content-center align-items-center">
    <div class="position-relative">
        <div class="card p-2 text-center">
            <h6>Please enter the one time password <br> to verify your account</h6>
            <div> <span>A code has been sent to</span> <small>Email</small> </div>
            <form method="post">
            {% csrf_token %}
            <div id="otp" class="inputs d-flex flex-row justify-content-center mt-2">
                <input class="m-2 text-center form-control rounded" type="text" id="id_otp" name="otp" maxlength="6" />
            </div>
            <div class="mt-4"> <button class="btn btn-danger px-4 validate">Validate</button> </div>
            </form>
        </div>
    </div>
  </div>

</body>
</html>